idf_component_register(
    SRCS
        "main_esp32.c"
        "hal_esp32_display.c"
        "hal_esp32_audio.c"
        "hal_esp32_input.c"
        "hal_esp32_system.c"
        "hal_esp32_power.c"
        "hal_esp32_storage.c"
        "../../src/app.c"
        "../../src/audio_player.c"
        "../../src/library/library.c"
        "../../src/ui/framebuffer.c"
        "../../src/ui/mini_player.c"
        "../../src/ui/themes.c"
        "../../src/ui/bsod.c"
        "../../src/ui/qrcodegen.c"
        "../../src/fonts/font_6x10.c"
        "../../src/fonts/font_8x13_bold.c"
        "../../src/codecs/decoder.c"
        "../../src/codecs/wav_decoder.c"
        "../../src/codecs/mp3_decoder.c"
        "../../src/codecs/flac_decoder.c"
        "../../src/codecs/art_decoder.c"
    INCLUDE_DIRS
        "."
        "../../include"
        "../../hal"
        "../../src"
        "../../src/codecs"
    REQUIRES
        esp_lcd
        esp_driver_i2s
        driver
        esp_timer
        freertos
        fatfs
)
